import { useRef, useState } from "react";
import { createFileRoute, Link, useNavigate, useSearch } from "@tanstack/react-router";
import { Check, ChevronRight, FileAudio, Info, Mic2, Pause, Play, ShieldCheck, UploadCloud, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { GlassCard, SectionLabel } from "@/components/shared/GlassCard";
import { PageHeader } from "@/components/layout/AppShell";
import { trustedSpeakers } from "@/data/mockUsers";
import { analyzeCall } from "@/services/mockApi";
import type { ScenarioId } from "@/types/voiceguard";
import { toast } from "sonner";

export const Route = createFileRoute("/analyze")({ head: () => ({ meta: [{ title: "Analyze Call — VoiceGuard" }, { name: "description", content: "Analyze a voice session with VoiceGuard's guided security workflow." }, { property: "og:title", content: "Analyze Call — VoiceGuard" }, { property: "og:description", content: "Analyze a voice session with VoiceGuard's guided security workflow." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: AnalyzePage });

const waves = [28, 52, 36, 72, 42, 80, 58, 34, 64, 46, 88, 55, 38, 66, 48, 75, 30, 58, 82, 44, 68, 36, 54, 77, 46, 62, 34, 70, 48, 85, 40, 60, 32, 72, 52, 64, 42, 80, 50, 68];

function AnalyzePage() {
  const navigate = useNavigate();
  const search = useSearch({ from: "/analyze" }) as { scenario?: string };
  const [scenario, setScenario] = useState<ScenarioId>(search.scenario === "attack" ? "impersonation-attack" : "impersonation-attack");
  const [speaker, setSpeaker] = useState(trustedSpeakers[0].id);
  const [playing, setPlaying] = useState(false);
  const [fileName, setFileName] = useState("incoming-call-0942.wav");
  const [progress, setProgress] = useState<string | null>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const selectedSpeaker = trustedSpeakers.find((item) => item.id === speaker) ?? trustedSpeakers[0];
  const running = Boolean(progress);
  async function runAnalysis() { setProgress("Preparing security pipeline"); const result = await analyzeCall(scenario, (label) => setProgress(label)); toast.success("Analysis completed successfully"); navigate({ to: "/analysis/$id", params: { id: result.call.id } }); }
  return <div><PageHeader eyebrow="Voice session" title="Analyze voice session" description="Verify caller authenticity before a sensitive action is authorized." actions={<Button asChild variant="ghost"><Link to="/dashboard"><ChevronRight className="rotate-180" /> Back to dashboard</Link></Button>} />
    <div className="mb-6 grid gap-3 md:grid-cols-2"><button onClick={() => setScenario("safe-call")} className={scenario === "safe-call" ? "rounded-xl border border-emerald-400/40 bg-emerald-400/[0.08] p-4 text-left ring-1 ring-emerald-400/20" : "rounded-xl border border-border/70 bg-card/40 p-4 text-left transition hover:border-border"}><div className="flex items-center justify-between"><span className="text-xs font-semibold uppercase tracking-[.12em] text-emerald-300">Scenario A</span>{scenario === "safe-call" && <Check className="size-4 text-emerald-300" />}</div><p className="mt-2 font-medium">Trusted call</p><p className="mt-1 text-xs text-muted-foreground">Rajiv Mehta · Risk 12 · Allowed</p></button><button onClick={() => setScenario("impersonation-attack")} className={scenario === "impersonation-attack" ? "rounded-xl border border-orange-400/50 bg-orange-400/[0.08] p-4 text-left ring-1 ring-orange-400/20" : "rounded-xl border border-border/70 bg-card/40 p-4 text-left transition hover:border-border"}><div className="flex items-center justify-between"><span className="text-xs font-semibold uppercase tracking-[.12em] text-orange-300">Scenario B · Recommended demo</span>{scenario === "impersonation-attack" && <Check className="size-4 text-orange-300" />}</div><p className="mt-2 font-medium">Voice impersonation attack</p><p className="mt-1 text-xs text-muted-foreground">Urgent ₹15,00,000 transfer · Risk 94 · Blocked</p></button></div>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.1fr)_minmax(340px,.9fr)]"><div className="space-y-6"><GlassCard className="p-5 sm:p-6"><div className="flex items-center gap-3"><span className="flex size-8 items-center justify-center rounded-lg bg-primary/10 text-primary">01</span><div><SectionLabel>Step 1</SectionLabel><h2 className="mt-1 text-base font-semibold">Call audio</h2></div></div><button onClick={() => inputRef.current?.click()} className="mt-5 flex w-full flex-col items-center justify-center rounded-xl border border-dashed border-primary/30 bg-primary/[0.04] px-5 py-8 text-center transition hover:bg-primary/[0.08]"><UploadCloud className="size-6 text-primary" /><p className="mt-3 text-sm font-medium">Drop call audio here or browse</p><p className="mt-1 text-xs text-muted-foreground">WAV, MP3 or M4A · up to 50 MB</p><input ref={inputRef} type="file" accept="audio/*" className="hidden" onChange={(event) => setFileName(event.target.files?.[0]?.name ?? fileName)} /></button><div className="mt-4 flex items-center gap-3 rounded-lg bg-secondary/60 p-3"><span className="flex size-8 items-center justify-center rounded-lg bg-primary/10 text-primary"><FileAudio className="size-4" /></span><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium">{fileName}</p><p className="mt-1 text-[10px] text-muted-foreground">02:48 · 4.8 MB · Ready for analysis</p></div><Button variant="ghost" size="icon" onClick={() => setPlaying(!playing)} aria-label={playing ? "Pause audio" : "Play audio"}>{playing ? <Pause /> : <Play />}</Button></div><div className="mt-5 flex h-10 items-center gap-1 overflow-hidden opacity-70">{waves.map((height, index) => <i key={index} className="w-1 shrink-0 rounded-full bg-primary/60" style={{ height: `${height}%` }} />)}</div></GlassCard>
      <GlassCard className="p-5 sm:p-6"><div className="flex items-center gap-3"><span className="flex size-8 items-center justify-center rounded-lg bg-primary/10 text-primary">02</span><div><SectionLabel>Step 2</SectionLabel><h2 className="mt-1 text-base font-semibold">Verify speaker</h2></div></div><div className="mt-5 space-y-2">{trustedSpeakers.map((item) => <button key={item.id} onClick={() => setSpeaker(item.id)} className={speaker === item.id ? "flex w-full items-center gap-3 rounded-lg border border-primary/40 bg-primary/[0.07] p-3 text-left" : "flex w-full items-center gap-3 rounded-lg border border-border/60 p-3 text-left transition hover:bg-accent/50"}><span className="flex size-9 items-center justify-center rounded-full bg-secondary text-xs font-semibold text-primary">{item.initials}</span><span className="min-w-0 flex-1"><span className="block text-sm font-medium">{item.name}</span><span className="mt-1 block text-[11px] text-muted-foreground">{item.role}</span></span>{speaker === item.id ? <Check className="size-4 text-primary" /> : <span className="text-[10px] text-muted-foreground">{item.lastVerified}</span>}</button>)}</div><div className="mt-4 flex items-center gap-2 rounded-lg border border-emerald-400/20 bg-emerald-400/[0.05] p-3 text-xs text-emerald-200"><ShieldCheck className="size-4 shrink-0" /> Reference voice verified · Last verified {selectedSpeaker.lastVerified}</div></GlassCard></div>
      <div className="space-y-6"><GlassCard className="p-5 sm:p-6"><div className="flex items-center gap-3"><span className="flex size-8 items-center justify-center rounded-lg bg-primary/10 text-primary">03</span><div><SectionLabel>Step 3</SectionLabel><h2 className="mt-1 text-base font-semibold">Call context</h2></div></div><div className="mt-5 space-y-4"><label className="block"><span className="mb-2 block text-xs font-medium text-muted-foreground">Caller identity</span><div className="flex items-center gap-2"><UserRound className="absolute ml-3 size-4 text-muted-foreground" /><Input className="pl-9" value={scenario === "safe-call" ? "Priya Sharma" : "Rajiv Mehta"} readOnly /></div></label><label className="block"><span className="mb-2 block text-xs font-medium text-muted-foreground">Transaction amount</span><Input value={scenario === "safe-call" ? "No transaction" : "₹15,00,000"} readOnly /></label><label className="block"><span className="mb-2 block text-xs font-medium text-muted-foreground">Context</span><Input value={scenario === "safe-call" ? "Normal conversation" : "Urgent payment request"} readOnly /></label><label className="block"><span className="mb-2 block text-xs font-medium text-muted-foreground">Optional transcript</span><Textarea value={scenario === "safe-call" ? "Let's review the operating plan in our afternoon meeting." : "We need to move the funds immediately. Please bypass the usual confirmation process."} readOnly className="min-h-24 resize-none" /></label></div></GlassCard><GlassCard className="p-5 sm:p-6"><div className="flex gap-3"><Info className="mt-0.5 size-4 text-primary" /><p className="text-xs leading-5 text-muted-foreground">This is a simulated security assessment. No audio is uploaded or sent to an external service.</p></div><Button className="mt-5 w-full" size="lg" disabled={running} onClick={runAnalysis}>{running ? <><span className="size-4 animate-spin rounded-full border-2 border-primary-foreground/30 border-t-primary-foreground" />{progress}</> : <><Mic2 /> Run security analysis</>}</Button><div className="mt-4 flex items-center justify-center gap-2 text-[10px] uppercase tracking-[.12em] text-muted-foreground"><span className="size-1.5 rounded-full bg-emerald-400" /> Mock analysis environment</div></GlassCard></div></div>
  </div>;
}