import { ArrowDownRight, ArrowUpRight, ChevronRight, LockKeyhole, ShieldAlert, Activity, AlertTriangle, CheckCircle2, Play, Plus, Radio, ShieldCheck } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Button } from "@/components/ui/button";
import { GlassCard, RiskBadge, SectionLabel, StatusDot } from "@/components/shared/GlassCard";
import { PageHeader } from "@/components/layout/AppShell";
import { RiskScore } from "@/components/shared/RiskScore";
import { dashboardMetrics, mockCalls, threatActivity } from "@/data/mockCalls";

const iconMap = { activity: Activity, shield: ShieldCheck, alert: ShieldAlert, lock: LockKeyhole };

export function DashboardPage() {
  return <div className="animate-in fade-in duration-500">
    <PageHeader eyebrow="Security overview" title="Good morning, Aarav" description="Your voice security perimeter is active and monitoring every sensitive conversation." actions={<><Button asChild variant="outline" className="border-border/70 bg-card/40"><Link to="/history">View activity <ChevronRight /></Link></Button><Button asChild><Link to="/analyze"><Plus /> Analyze call</Link></Button></>} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{dashboardMetrics.map((metric) => { const Icon = iconMap[metric.icon as keyof typeof iconMap]; return <GlassCard key={metric.label} className="p-4"><div className="flex items-start justify-between"><span className="flex size-8 items-center justify-center rounded-lg bg-secondary text-primary"><Icon className="size-4" /></span><span className={metric.trend === "down" ? "flex items-center gap-1 text-[11px] text-emerald-300" : "flex items-center gap-1 text-[11px] text-primary"}>{metric.trend === "down" ? <ArrowDownRight className="size-3" /> : <ArrowUpRight className="size-3" />}{metric.change}</span></div><p className="mt-5 text-2xl font-semibold tracking-tight">{metric.value}</p><p className="mt-1 text-xs text-muted-foreground">{metric.label}</p></GlassCard>; })}</div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.45fr)_minmax(300px,.55fr)]">
      <GlassCard className="min-w-0 p-5 sm:p-6"><div className="flex items-start justify-between"><div><SectionLabel>Live telemetry</SectionLabel><h2 className="mt-2 text-lg font-semibold">Real-time threat activity</h2><p className="mt-1 text-xs text-muted-foreground">Call security signals across the last 12 hours</p></div><div className="flex items-center gap-3 text-[10px] text-muted-foreground"><span className="flex items-center gap-1.5"><i className="size-1.5 rounded-full bg-primary" />Safe</span><span className="flex items-center gap-1.5"><i className="size-1.5 rounded-full bg-amber-400" />Suspicious</span><span className="flex items-center gap-1.5"><i className="size-1.5 rounded-full bg-red-400" />Critical</span></div></div><div className="mt-6 h-[250px] w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={threatActivity} margin={{ top: 8, right: 8, left: -24, bottom: 0 }}><defs><linearGradient id="safeFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--primary)" stopOpacity={0.22} /><stop offset="100%" stopColor="var(--primary)" stopOpacity={0} /></linearGradient><linearGradient id="criticalFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--danger)" stopOpacity={0.22} /><stop offset="100%" stopColor="var(--danger)" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="var(--border)" strokeDasharray="3 3" vertical={false} /><XAxis dataKey="time" tick={{ fill: "var(--muted-foreground)", fontSize: 10 }} axisLine={false} tickLine={false} /><YAxis tick={{ fill: "var(--muted-foreground)", fontSize: 10 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={{ background: "var(--popover)", border: "1px solid var(--border)", borderRadius: 10, fontSize: 11 }} /><Area type="monotone" dataKey="safe" stroke="var(--primary)" fill="url(#safeFill)" strokeWidth={2} /><Area type="monotone" dataKey="suspicious" stroke="var(--warning)" fill="none" strokeWidth={1.5} /><Area type="monotone" dataKey="critical" stroke="var(--danger)" fill="url(#criticalFill)" strokeWidth={1.5} /></AreaChart></ResponsiveContainer></div></GlassCard>
      <GlassCard className="p-5 sm:p-6"><div className="flex items-start justify-between"><div><SectionLabel>Engine status</SectionLabel><h2 className="mt-2 text-lg font-semibold">Protection active</h2></div><Radio className="size-5 text-primary" /></div><div className="mt-6 space-y-5">{["Voice analysis engine", "Speaker verification", "Risk engine", "Security gateway"].map((engine) => <div key={engine} className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><StatusDot /><span className="text-sm text-muted-foreground">{engine}</span></div><span className="text-[10px] font-semibold uppercase tracking-[.12em] text-emerald-300">Ready</span></div>)}</div><div className="mt-7 border-t border-border/60 pt-4"><div className="flex items-center justify-between text-xs"><span className="text-muted-foreground">System confidence</span><span className="font-medium text-primary">99.98%</span></div><div className="mt-3 h-1.5 rounded-full bg-muted"><div className="h-full w-[98%] rounded-full bg-primary" /></div></div></GlassCard>
    </div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.45fr)_minmax(300px,.55fr)]">
      <GlassCard className="p-5 sm:p-6"><div className="flex items-center justify-between"><div><SectionLabel>Event stream</SectionLabel><h2 className="mt-2 text-lg font-semibold">Recent security events</h2></div><Button asChild variant="ghost" size="sm" className="text-muted-foreground"><Link to="/history">View all <ChevronRight /></Link></Button></div><div className="mt-4 divide-y divide-border/60">{mockCalls.slice(0, 3).map((call) => <div key={call.id} className="flex items-center gap-3 py-4"><div className={call.riskLevel === "trusted" ? "flex size-9 items-center justify-center rounded-lg bg-emerald-400/10 text-emerald-300" : "flex size-9 items-center justify-center rounded-lg bg-red-400/10 text-red-300"}>{call.riskLevel === "trusted" ? <CheckCircle2 className="size-4" /> : <AlertTriangle className="size-4" />}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="truncate text-sm font-medium">{call.intent}</p><RiskBadge tone={call.riskLevel}>{call.riskLevel === "trusted" ? "Allowed" : call.decision === "blocked" ? "Blocked" : "Review"}</RiskBadge></div><p className="mt-1 text-xs text-muted-foreground">{call.time} <span className="mx-1">·</span> Caller: {call.caller}</p></div><RiskScore score={call.risk} tone={call.riskLevel} compact /></div>)}</div></GlassCard>
      <GlassCard className="relative overflow-hidden bg-primary/[0.06] p-5 sm:p-6"><div className="absolute -right-12 -top-12 size-36 rounded-full border border-primary/10" /><div className="absolute -right-7 -top-7 size-26 rounded-full border border-primary/10" /><SectionLabel>Demo scenario</SectionLabel><h2 className="mt-3 text-lg font-semibold">Test an attack path</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Walk through a simulated voice impersonation attempt from detection to transaction block.</p><Button asChild className="mt-6 w-full"><Link to="/analyze?scenario=attack"><Play className="size-4" /> Run attack demo</Link></Button><p className="mt-3 text-center text-[10px] uppercase tracking-[.12em] text-muted-foreground">No live audio or external services</p></GlassCard>
    </div>
  </div>;
}